=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/metaData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.likyateknoloji.com/XML_metaData_types" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.likyateknoloji.com/XML_metaData_types" elementFormDefault="qualified">
  <xs:element name="metaData">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dbInfo"/>
        <xs:element ref="documentInfo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dbInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="prefix"/>
        <xs:element ref="rootCollection"/>
        <xs:element maxOccurs="unbounded" ref="collection"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="prefix" type="xs:string"/>
  <xs:element name="rootCollection" type="xs:NCName"/>
  <xs:element name="collection">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="documentInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="document"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="document">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="id" use="required" type="xs:NCName"/>
          <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xml/metaData.xml
<?xml version="1.0"?>
<meta:metaData xmlns:meta="http://www.likyateknoloji.com/XML_metaData_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.likyateknoloji.com/XML_metaData_types ../xsds/metaData.xsd">
	<meta:dbInfo>
		<meta:name>Exist Db</meta:name>
		<meta:prefix>//db/</meta:prefix>
		<meta:rootCollection>TLOSSW</meta:rootCollection>
		<meta:collection type="module">modules</meta:collection>
		<meta:collection type="xml">xmls</meta:collection>
		<meta:collection type="xsd">xsds</meta:collection>
		<meta:collection type="xsl">xsls</meta:collection>
	</meta:dbInfo>
	<meta:documentInfo>
		<meta:document id="agentConfig" type="xml">tlosSWAgentConfig10.xml</meta:document>
		<meta:document id="agents" type="xml">tlosSWAgents10.xml</meta:document>
		<meta:document id="alarms" type="xml">tlosSWAlarm10.xml</meta:document>
		<meta:document id="alarmHistory" type="xml">tlosSWAlarmHistory10.xml</meta:document>
		<meta:document id="calendar" type="xml">tlosSWCalendar10.xml</meta:document>
		<meta:document id="serverConfig" type="xml">tlosSWConfig10.xml</meta:document>
		<meta:document id="plan" type="xml">tlosSWDailyPlan10.xml</meta:document>
		<meta:document id="scenarios" type="xml">tlosSWDailyScenarios10.xml</meta:document>
		<meta:document id="sjData" type="xml">tlosSWData10.xml</meta:document>
		<meta:document id="dbConnectionProfiles" type="xml">tlosSWDBConnectionProfiles10.xml</meta:document>
		<meta:document id="dbConnections" type="xml">tlosSWDBConnections10.xml</meta:document>
		<meta:document id="errors" type="xml">tlosSWErrors10.xml</meta:document>
		<meta:document id="globalStates" type="xml">tlosSWGlobalStates10.xml</meta:document>
		<meta:document id="jobTemplates" type="xml">tlosSWJobTemplates10.xml</meta:document>
		<meta:document id="nrpeData" type="xsl">tlosSWNrpeData10.xml</meta:document>
		<meta:document id="nrpeResult" type="xsl">tlosSWNrpeResult_v_1_0.xml</meta:document>
		<meta:document id="parameters" type="xsl">tlosSWParameters10.xml</meta:document>
		<meta:document id="permissions" type="xsl">tlosSWPermission10.xml</meta:document>
		<meta:document id="programProvisioning" type="xml">tlosSWProgramProvisioning10.xml</meta:document>
		<meta:document id="reports" type="xml">tlosSWReports10.xml</meta:document>
		<meta:document id="resources" type="xml">tlosSWResources10.xml</meta:document>
		<meta:document id="sequenceData" type="xml">tlosSWSequenceData10.xml</meta:document>
		<meta:document id="jobFileListener" type="xml">tlosSWSJFileListener10.xml</meta:document>
		<meta:document id="ftpConnnections" type="xml">tlosSWSJFTPConnections10.xml</meta:document>
		<meta:document id="jobWebServices" type="xml">tlosSWSJWebServices10.xml</meta:document>
		<meta:document id="sla" type="xml">tlosSWSLAs10.xml</meta:document>
		<meta:document id="trace" type="xml">tlosSWTrace10.xml</meta:document>
		<meta:document id="user" type="xml">tlosSWUser10.xml</meta:document>
		<meta:document id="wsAccessProfiles" type="xml">tlosSWWebServiceAccessProfiles10.xml</meta:document>
		<meta:document id="xmlTransformXsl" type="xsl">tlosXMLTransformXsl.xsl</meta:document>
		<meta:document id="jobTransform" type="xsl">tlosJobTransform.xsl</meta:document>
		<meta:document id="dataFo" type="xsl">tlosDataFo.xsl</meta:document>
		<meta:document id="dataXsl" type="xsl">tlosData.xsl</meta:document>
	</meta:documentInfo>
</meta:metaData>
