=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWDBConnections_v_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.likyateknoloji.com/XML_dbconnection_types" xmlns:com="http://www.likyateknoloji.com/XML_common_types"
           xmlns:dbc="http://www.likyateknoloji.com/XML_dbconnection_types">
	<xs:import namespace="http://www.likyateknoloji.com/XML_common_types" schemaLocation="tlosSWOrtak_v_1_0.xsd"/>
	
	<xs:element name="dbList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dbc:dbProperties" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="connectionNameUniqueKey">
			<xs:selector xpath="dbc:dbProperties"/>
			<xs:field xpath="dbc:connectionName"/>
		</xs:unique>
	</xs:element>
	
	<xs:element name="dbProperties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dbc:connectionName"/>
				<xs:element ref="dbc:dbUrl"/>
				<xs:element ref="dbc:dbType"/>
				<xs:element ref="dbc:dbVersion"/>
				<xs:element ref="dbc:driverName"/>
				<xs:element ref="dbc:dbName"/>
				<xs:element ref="dbc:hostName"/>
				<xs:element name="listenerPortNumber" type="com:portType"/>
				<xs:element name="ipAddress" type="com:ipAddressType"/>
				<xs:element ref="dbc:jdbcClassName"/>
				<xs:element ref="dbc:sqlClientAppName" minOccurs="0"/> <!-- free sqlde kullanilmiyor -->
				<xs:element ref="dbc:sqlClientAppPath" minOccurs="0"/> <!-- free sqlde kullanilmiyor -->
			</xs:sequence>
			<xs:attribute name="ID" use="required" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="connectionName" type="xs:string"/>
	<xs:element name="dbUrl" type="xs:string"/>
	<xs:element name="dbVersion" type="xs:string"/>
	<xs:element name="jdbcClassName" type="xs:string"/>

	<xs:element name="dbType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="PostgreSQL"/>
				<xs:enumeration value="Oracle"/>
				<xs:enumeration value="SQLServer"/>
				<xs:enumeration value="SAS"/>
				<xs:enumeration value="MySQL"/>
				<xs:enumeration value="DB2"/>
				<xs:enumeration value="Informix"/>
				<xs:enumeration value="Firebird"/>
				<xs:enumeration value="Sybase"/>
				<xs:enumeration value="Teradata"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="deployed" default="no">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="yes"/>
				<xs:enumeration value="no"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="driverName" type="xs:NCName"/>
	<xs:element name="dbName" type="xs:string"/>
	<xs:element name="hostName" type="xs:string"/>
	<xs:element name="jdbcConnectionPoolParams">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dbc:initialCapacity"/>
				<xs:element ref="dbc:maxCapacity"/>
				<xs:element ref="dbc:minIdle"/>
				<xs:element ref="dbc:maxIdle"/>
				<xs:element ref="dbc:maxWait"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="initialCapacity" type="xs:integer" default="3"/>
	<xs:element name="maxCapacity" type="xs:integer" default="10"/>
	<xs:element name="minIdle" type="xs:integer" default="0"/>
	<xs:element name="maxIdle" type="xs:integer" default="0"/>
	<xs:element name="maxWait" type="xs:integer" default="10000"/>

	<xs:element name="sqlClientAppName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="sqlplus"/> <!-- oracle -->
				<xs:enumeration value="psql"/> <!-- postgresql -->
				<xs:enumeration value="mysql"/> <!-- mysql -->
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="sqlClientAppPath" type="xs:string"/>

	<xs:element name="dbConnectionProfiles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dbc:dbConnectionProfile" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="profileName" type="xs:string"/>

	<xs:element name="dbConnectionProfile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dbc:dbDefinitionId"/>
				<xs:element ref="dbc:profileName"/>
				<xs:element ref="com:userName"/>
				<xs:element ref="com:userPassword"/>
				<xs:element ref="dbc:jdbcConnectionPoolParams"/>
				<xs:element ref="dbc:deployed"/>
				<xs:element ref="com:active"/>
			</xs:sequence>
			<xs:attribute name="ID" use="required" type="xs:integer"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="dbDefinitionId" type="xs:integer"/>
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xmls/tlosSWDBConnections10.xml
<dbc:dbList xmlns:dbc="http://www.likyateknoloji.com/XML_dbconnection_types"
	xmlns:com="http://www.likyateknoloji.com/XML_common_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.likyateknoloji.com/XML_dbconnection_types  ../xsds/tlosSWDBConnections_v_1_0.xsd">
	<dbc:dbProperties ID="4">
		<dbc:connectionName>Centos</dbc:connectionName>
		<dbc:dbUrl>jdbc:postgresql://</dbc:dbUrl>
		<dbc:dbType>PostgreSQL</dbc:dbType>
		<dbc:dbVersion>9.1</dbc:dbVersion>
		<dbc:driverName>JDBC</dbc:driverName>
		<dbc:dbName>test</dbc:dbName>
		<dbc:hostName>192.168.1.70</dbc:hostName>
		<dbc:listenerPortNumber>5432</dbc:listenerPortNumber>
		<dbc:ipAddress>192.168.1.70</dbc:ipAddress>
		<dbc:jdbcClassName>className</dbc:jdbcClassName>
		<dbc:sqlClientAppName>psql</dbc:sqlClientAppName>
		<dbc:sqlClientAppPath>D:\postgresql-9.2.4-1-windows-x64-binaries\pgsql\bin\
		</dbc:sqlClientAppPath>
	</dbc:dbProperties>
	<dbc:dbProperties ID="5">
		<dbc:connectionName>oracle_75</dbc:connectionName>
		<dbc:dbUrl>jdbc:oracle:thin:</dbc:dbUrl>
		<dbc:dbType>Oracle</dbc:dbType>
		<dbc:dbVersion>11</dbc:dbVersion>
		<dbc:driverName>JDBC</dbc:driverName>
		<dbc:dbName>orcl</dbc:dbName>
		<dbc:hostName>192.168.1.75</dbc:hostName>
		<dbc:listenerPortNumber>1521</dbc:listenerPortNumber>
		<dbc:ipAddress>192.168.1.75</dbc:ipAddress>
		<dbc:jdbcClassName>className</dbc:jdbcClassName>
		<dbc:sqlClientAppName>sqlplus</dbc:sqlClientAppName>
		<dbc:sqlClientAppPath>D:\instantclient-basic-windows.x64-11.2.0.3.0\instantclient_11_2\
		</dbc:sqlClientAppPath>
	</dbc:dbProperties>
	<dbc:dbProperties ID="6">
		<dbc:connectionName>centos_postgres</dbc:connectionName>
		<dbc:dbUrl>jdbc:postgresql://</dbc:dbUrl>
		<dbc:dbType>PostgreSQL</dbc:dbType>
		<dbc:dbVersion>9.1</dbc:dbVersion>
		<dbc:driverName>JDBC</dbc:driverName>
		<dbc:dbName>postgres</dbc:dbName>
		<dbc:hostName>192.168.1.70</dbc:hostName>
		<dbc:listenerPortNumber>5432</dbc:listenerPortNumber>
		<dbc:ipAddress>192.168.1.70</dbc:ipAddress>
		<dbc:jdbcClassName>className</dbc:jdbcClassName>
		<dbc:sqlClientAppName>psql</dbc:sqlClientAppName>
		<dbc:sqlClientAppPath>D:\postgresql-9.2.4-1-windows-x64-binaries\pgsql\bin\</dbc:sqlClientAppPath>
	</dbc:dbProperties>
    <dbc:dbProperties ID="11">
        <dbc:connectionName>ayhandb</dbc:connectionName>
        <dbc:dbUrl>jdbc:oracle:thin:</dbc:dbUrl>
        <dbc:dbType>Oracle</dbc:dbType>
        <dbc:dbVersion>11</dbc:dbVersion>
        <dbc:driverName>JDBC</dbc:driverName>
        <dbc:dbName>orcl</dbc:dbName>
        <dbc:hostName>ayhan-laptop2</dbc:hostName>
        <dbc:listenerPortNumber>1523</dbc:listenerPortNumber>
        <dbc:ipAddress>192.168.1.210</dbc:ipAddress>
        <dbc:jdbcClassName>className</dbc:jdbcClassName>
        <dbc:sqlClientAppName>sqlplus</dbc:sqlClientAppName>
        <dbc:sqlClientAppPath>D:\likya\projeler\tlos\tlos3.0\dss_module</dbc:sqlClientAppPath>
    </dbc:dbProperties>
</dbc:dbList>

=== likyateknoloji/TlosSWGroup/TlosSWServerTester/src/DBOracleConnection.xml
<dbc:dbProperties ID="1" xmlns:dbc="http://www.likyateknoloji.com/XML_dbconnection_types" xmlns:com="http://www.likyateknoloji.com/XML_common_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.likyateknoloji.com/XML_dbconnection_types  xmldb:exist:///db/TLOSSW/xsds/tlosSWDBConnections_v_1_0.xsd">
        <dbc:connectionName>Oracle Connection</dbc:connectionName>
        <dbc:dbUrl>jdbc:oracle:thin:</dbc:dbUrl>
        <dbc:dbType>Oracle</dbc:dbType>
        <dbc:dbVersion>11</dbc:dbVersion>
        <dbc:driverName>JDBC</dbc:driverName>
        <dbc:dbName>orcl</dbc:dbName>
        <dbc:hostName>192.168.1.75</dbc:hostName>
        <dbc:listenerPortNumber>1521</dbc:listenerPortNumber>
        <com:ipAddress>192.168.1.75</com:ipAddress>
        <dbc:jdbcClassName>className</dbc:jdbcClassName>
 		<dbc:sqlClientAppName>sqlplus</dbc:sqlClientAppName>
		<dbc:sqlClientAppPath>C:\app\ayhan\product\11.2.0\dbhome_2\BIN\</dbc:sqlClientAppPath>
    </dbc:dbProperties>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xml/tlosSWDBConnections10.xml
<dbc:dbList xmlns:dbc="http://www.likyateknoloji.com/XML_dbconnection_types" xmlns:com="http://www.likyateknoloji.com/XML_common_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.likyateknoloji.com/XML_dbconnection_types  xmldb:exist:///db/TLOSSW/xsds/tlosSWDBConnections_v_1_0.xsd">
    <dbc:dbProperties ID="1">
        <dbc:connectionName>PostgreSQL Connection</dbc:connectionName>
        <dbc:dbUrl>jdbc:postgresql://</dbc:dbUrl>
        <dbc:dbType>PostgreSQL</dbc:dbType>
        <dbc:dbVersion>9.1</dbc:dbVersion>
        <dbc:driverName>JDBC</dbc:driverName>
        <dbc:dbName>Carre</dbc:dbName>
        <dbc:hostName>ayhan-laptop2</dbc:hostName>
        <dbc:listenerPortNumber>5432</dbc:listenerPortNumber>
        <com:ipAddress>127.0.0.1</com:ipAddress>
        <dbc:jdbcClassName>className</dbc:jdbcClassName>
		<dbc:sqlClientAppName>psql</dbc:sqlClientAppName>
		<dbc:sqlClientAppPath>C:/Program Files/PostgreSQL/9.1/bin/</dbc:sqlClientAppPath>
    </dbc:dbProperties>
    <dbc:dbProperties ID="2">
        <dbc:connectionName>Oracle Connection</dbc:connectionName>
        <dbc:dbUrl>jdbc:oracle:thin:</dbc:dbUrl>
        <dbc:dbType>Oracle</dbc:dbType>
        <dbc:dbVersion>11</dbc:dbVersion>
        <dbc:driverName>JDBC</dbc:driverName>
        <dbc:dbName>oralikya</dbc:dbName>
        <dbc:hostName>localhost</dbc:hostName>
        <dbc:listenerPortNumber>1521</dbc:listenerPortNumber>
        <com:ipAddress>127.0.0.1</com:ipAddress>
        <dbc:jdbcClassName>className</dbc:jdbcClassName>
 		<dbc:sqlClientAppName>sqlplus</dbc:sqlClientAppName>
		<dbc:sqlClientAppPath>C:\app\ayhan\product\11.2.0\dbhome_2\BIN\</dbc:sqlClientAppPath>        
    </dbc:dbProperties>
</dbc:dbList>
