=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWSLA_v_1_0.xsd
<xs:schema xmlns="http://www.likyateknoloji.com/XML_SLA_types" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:lt="http://www.likyateknoloji.com/XML_common_types" elementFormDefault="qualified" targetNamespace="http://www.likyateknoloji.com/XML_SLA_types">
    <xs:import namespace="http://www.likyateknoloji.com/XML_common_types" schemaLocation="tlosSWOrtak_v_1_0.xsd"/>
    <xs:element name="ServiceLevelAgreement">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="SLA"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="SLA">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Organization"/>
                <xs:element ref="Name"/>
                <xs:element ref="Desc"/>
                <xs:element ref="CreationDate"/>
                <xs:element ref="StartDate"/>
                <xs:element ref="EndDate"/>
                <xs:element ref="lt:timeZone" minOccurs="0"/>
                <xs:element ref="lt:typeOfTime" minOccurs="0"/>
                <xs:element ref="SInterval"/>
                <xs:element ref="RInterval"/>
                <xs:element ref="Priority"/>
                <xs:element ref="ResourcePool"/>
                <xs:element ref="ResourceReq"/>
                <xs:element ref="calendarId"/>
                <xs:element ref="QueueFrame"/>
                <xs:element ref="ResolveIncident"/>
                <xs:element ref="JobsInStatus"/>
                <xs:element ref="lt:userId"/>
            </xs:sequence>
            <xs:attribute name="ID" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Organization" type="xs:NCName"/>
    <xs:element name="Name" type="xs:string"/>
    <xs:element name="Desc" type="xs:string"/>
    <xs:element name="CreationDate" type="xs:dateTime"/>
    <xs:element name="StartDate" type="xs:dateTime"/>
    <xs:element name="EndDate" type="xs:dateTime"/>
    <xs:element name="SInterval">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="startTime"/>
                <xs:element ref="stopTime"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="RInterval">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="startTime"/>
                <xs:element ref="stopTime"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Priority" type="xs:integer"/>
    <xs:element name="ResourcePool">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="Resource"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Resource">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="order" use="required" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="ResourceReq">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Hardware"/>
                <xs:element ref="Software"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Hardware">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="mem"/>
                <xs:element ref="cpu"/>
                <xs:element ref="disk"/>
            </xs:sequence>
            <xs:attribute name="entry-name" use="optional" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="birim">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="%"/>
                <xs:enumeration value="G"/>
                <xs:enumeration value="M"/>
                <xs:enumeration value="K"/>
                <xs:enumeration value="B"/>
                <xs:enumeration value="Sec"/>
                <xs:enumeration value="Min"/>
                <xs:enumeration value="Hour"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="timein">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="1"/>
                <xs:enumeration value="5"/>
                <xs:enumeration value="15"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="for">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="used"/>
                <xs:enumeration value="free"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="condition">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="gt"/>
                <xs:enumeration value="lt"/>
                <xs:enumeration value="eq"/>
                <xs:enumeration value="ge"/>
                <xs:enumeration value="le"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:element name="mem">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute ref="birim" use="required"/>
                    <xs:attribute ref="condition" use="required"/>
                    <xs:attribute ref="for" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="cpu">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute ref="birim" use="required"/>
                    <xs:attribute ref="condition" use="required"/>
                    <xs:attribute ref="timein" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="disk">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute ref="birim" use="required"/>
                    <xs:attribute ref="condition" use="required"/>
                    <xs:attribute ref="for" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Software">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Program"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="ProgramType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="licenseID" use="required" type="xs:nonNegativeInteger"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="Program" type="ProgramType"/>
	<!--
	<xs:element name="Program">
		<xs:complexType mixed="true">
			<xs:attribute name="licenseID" use="required" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	-->
    <xs:element name="calendarId" type="xs:nonNegativeInteger"/>
    <xs:element name="QueueFrame">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="MaxTimeInQueue"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="MaxTimeInQueue">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:nonNegativeInteger">
                    <xs:attribute ref="birim" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="ResolveIncident">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="MaxTimeToResolve"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="MaxTimeToResolve">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:nonNegativeInteger">
                    <xs:attribute ref="birim" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="JobsInStatus">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="NumberOfJobs"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="state">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="PENDING"/>
                <xs:enumeration value="RUNNING"/>
                <xs:enumeration value="CANCELLED"/>
                <xs:enumeration value="FAILED"/>
                <xs:enumeration value="FINISHED"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:element name="NumberOfJobs">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute ref="state"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="startTime" type="xs:time"/>
    <xs:element name="stopTime" type="xs:time"/>
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xml/tlosSWSLAs10.xml
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<sla:ServiceLevelAgreement xmlns:sla="http://www.likyateknoloji.com/XML_SLA_types" xmlns:com="http://www.likyateknoloji.com/XML_common_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.likyateknoloji.com/XML_SLA_types xmldb:exist:///db/TLOSSW/xsds/tlosSWSLA_v_1_0.xsd http://www.likyateknoloji.com/XML_common_types xmldb:exist:///db/TLOSSW/xsds/tlosSWOrtak_v_1_0.xsd">
    <sla:SLA ID="1">
        <sla:Organization>Yok</sla:Organization>
        <sla:Name>Genel SLA</sla:Name>
        <sla:Desc>Joblarin her birisinin dagitilmasi sirasinda uyulacak genel SLA</sla:Desc>
        <sla:CreationDate>2011-05-30T09:30:10+02:00</sla:CreationDate>
        <sla:StartDate>2011-05-30T09:30:10+02:00</sla:StartDate>
        <sla:EndDate>2012-05-30T09:30:10+02:00</sla:EndDate>
        <sla:SInterval>
            <sla:startTime>01:00:00+02:00</sla:startTime>
            <sla:stopTime>22:30:00+02:00</sla:stopTime>
        </sla:SInterval>
        <sla:RInterval>
            <sla:startTime>11:00:00+02:00</sla:startTime>
            <sla:stopTime>12:30:00+02:00</sla:stopTime>
        </sla:RInterval>
        <sla:Priority>1</sla:Priority>
        <sla:ResourcePool>
		</sla:ResourcePool>
        <sla:ResourceReq>
            <sla:Hardware>
                <sla:mem sla:birim="G" sla:for="free" sla:condition="gt">2</sla:mem>
                <sla:cpu sla:birim="%" sla:timein="1" sla:condition="lt">80</sla:cpu>
                <sla:disk sla:birim="G" sla:for="free" sla:condition="gt">2</sla:disk>
            </sla:Hardware>
            <sla:Software>
                <sla:Program licenseID="1">Tlos SW</sla:Program>
                <sla:Program licenseID="2">SAS</sla:Program>
            </sla:Software>
        </sla:ResourceReq>
        <sla:calendarId>1</sla:calendarId>
        <sla:QueueFrame>
            <sla:MaxTimeInQueue sla:birim="Min">100</sla:MaxTimeInQueue>
        </sla:QueueFrame>
        <sla:ResolveIncident>
            <sla:MaxTimeToResolve sla:birim="Min">30</sla:MaxTimeToResolve>
        </sla:ResolveIncident>
        <sla:JobsInStatus>
            <sla:NumberOfJobs sla:state="RUNNING">10</sla:NumberOfJobs>
        </sla:JobsInStatus>
        <com:userId>1</com:userId>
    </sla:SLA>
    <sla:SLA ID="2">
        <sla:Organization>XXX</sla:Organization>
        <sla:Name>Gune ozel SLA</sla:Name>
        <sla:Desc>Istenen Kaynak(lar) belirli gunlerde kullanilma(ma)li</sla:Desc>
        <sla:CreationDate>2011-05-30T09:30:10+06:00</sla:CreationDate>
        <sla:StartDate>2011-05-30T09:30:10+06:00</sla:StartDate>
        <sla:EndDate>2012-05-30T09:30:10+06:00</sla:EndDate>
        <sla:SInterval>
            <sla:startTime>01:00:00+02:00</sla:startTime>
            <sla:stopTime>22:30:00+02:00</sla:stopTime>
        </sla:SInterval>
        <sla:RInterval>
            <sla:startTime>11:00:00+02:00</sla:startTime>
            <sla:stopTime>12:30:00+02:00</sla:stopTime>
        </sla:RInterval>
        <sla:Priority>1</sla:Priority>
        <sla:ResourcePool>
            <sla:Resource order="1">laptop-hakan</sla:Resource>
        </sla:ResourcePool>
        <sla:ResourceReq>
            <sla:Hardware>
                <sla:mem sla:birim="M" sla:for="free" sla:condition="gt">2048</sla:mem>
                <sla:cpu sla:birim="%" sla:timein="1" sla:condition="lt">80</sla:cpu>
                <sla:disk sla:birim="K" sla:for="free" sla:condition="gt">2097152</sla:disk>
            </sla:Hardware>
            <sla:Software>
                <sla:Program licenseID="2">SAS</sla:Program>
            </sla:Software>
        </sla:ResourceReq>
        <sla:calendarId>1</sla:calendarId>
        <sla:QueueFrame>
            <sla:MaxTimeInQueue sla:birim="Min">100</sla:MaxTimeInQueue>
        </sla:QueueFrame>
        <sla:ResolveIncident>
            <sla:MaxTimeToResolve sla:birim="Min">30</sla:MaxTimeToResolve>
        </sla:ResolveIncident>
        <sla:JobsInStatus>
            <sla:NumberOfJobs sla:state="RUNNING">3</sla:NumberOfJobs>
        </sla:JobsInStatus>
        <com:userId>1</com:userId>
    </sla:SLA>
</sla:ServiceLevelAgreement>
