=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWTrace_v_1_0.xsd
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<xs:schema xmlns="http://www.likyateknoloji.com/XML_trace_types" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:lt="http://www.likyateknoloji.com/XML_common_types" targetNamespace="http://www.likyateknoloji.com/XML_trace_types" elementFormDefault="qualified">
    <xs:import namespace="http://www.likyateknoloji.com/XML_common_types" schemaLocation="tlosSWOrtak_v_1_0.xsd"/>
    
     <xs:element name="TlosTraceData">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="trace"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="trace">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="trcTime"/>
                <xs:element ref="trcUser"/>
                <xs:element ref="trcUserAgent"/>
                <xs:element ref="trcSource"/>
                <xs:element name="componentId" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
            	<xs:simpleType>
                    <xs:restriction base="xs:int"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="trcTimeValue">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
    
    <xs:element name="trcTime">
       <xs:complexType>
		  <xs:simpleContent>
			<xs:extension base="trcTimeValue">
			  <xs:attribute name="millis" type="xs:long" use="required"/>
			</xs:extension>
		  </xs:simpleContent>
        </xs:complexType>
   </xs:element>
    
    <xs:simpleType name="trcUserValue">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:element name="trcUser">
        <xs:complexType>
		  <xs:simpleContent>
			<xs:extension base="trcUserValue">
	            <xs:attribute name="id" type="xs:int" use="optional"/>
	            <xs:attribute name="password" type="xs:string" use="optional"/>
	            <xs:attribute name="role" type="xs:string" use="optional"/>
	         </xs:extension>
		 </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="trcUserAgentValue">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:element name="trcUserAgent">
        <xs:complexType>
        	<xs:simpleContent>
			   <xs:extension base="trcUserAgentValue">
	            <xs:attribute name="ip" use="optional">
		            <xs:simpleType>
			            <xs:restriction base="xs:string">
			                <xs:pattern value="[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"/>
			            </xs:restriction>
		        	</xs:simpleType>
	            </xs:attribute>
	         </xs:extension>
		   </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="trcSourceValue">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:element name="trcSource">
        <xs:complexType>
        	<xs:simpleContent>
				<xs:extension base="trcSourceValue">
		            <xs:attribute name="javaProject" type="xs:string" default="TlosEntWeb"/>
		            <xs:attribute name="package" type="xs:string" use="required"/>
		            <xs:attribute name="class" type="xs:string" use="required"/>
		            <xs:attribute name="method" type="xs:string" use="required"/>
	         	</xs:extension>
		    </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xml/tlosSWTrace10.xml
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<trc:TlosTraceData xmlns:trc="http://www.likyateknoloji.com/XML_trace_types" xmlns:com="http://www.likyateknoloji.com/XML_common_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.likyateknoloji.com/XML_trace_types xmldb:exist:///db/TLOSSW/xsds/tlosSWTrace_v_1_0.xsd">
    <trc:trace id="1">
        <trc:trcTime millis="1084224175321">2004-05-10 17:22:55.321-01:00</trc:trcTime>
        <trc:trcUser id="12" password="1234" role="admin">Hasan</trc:trcUser>
        <trc:trcUserAgent ip="192.168.1.1">Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.19) Gecko/2010031422 Firefox/3.0.19 (.NET CLR 3.5.30729)</trc:trcUserAgent>
        <trc:trcSource javaProject="TlosEntWeb" package="com.likya.tlos.appmng.workspace" class="ScenarioMBean.java" method="jobInsertAction">tlos.login.invalidLogin</trc:trcSource>
        <trc:componentId>JobInsertButton</trc:componentId>
        <trc:description>job id="18" name="job10" path="freeJobs"</trc:description>
    </trc:trace>
</trc:TlosTraceData>
