=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWReports_v_1_0.xsd
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<xs:schema xmlns="http://www.likyateknoloji.com/XML_report_types" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.likyateknoloji.com/XML_report_types" elementFormDefault="qualified">
    <xs:element name="reportAll">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="stateReport"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="stateReport">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="report" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="report">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="PENDING"/>
                <xs:element ref="RUNNING"/>
                <xs:element ref="FAILED"/>
                <xs:element ref="CANCELLED"/>
                <xs:element ref="FINISHED"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
            <xs:attribute name="jsId" use="required" type="xs:integer"/>
            <xs:attribute name="scope" use="required" type="xs:string"/>
            <xs:attribute name="LSIDateTime" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:dateTime"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="PENDING">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="CREATED"/>
                <xs:element ref="DEACTIVATED"/>
                <xs:element ref="VALIDATED"/>
                <xs:element ref="IDLED"/>
                <xs:element ref="READY"/>
                <xs:element ref="PAUSED"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="CREATED" type="xs:integer"/>
    <xs:element name="DEACTIVATED" type="xs:integer"/>
    <xs:element name="VALIDATED" type="xs:integer"/>
    <xs:element name="IDLED">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="BYTIME"/>
				<xs:element ref="BYUSER"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="BYTIME" type="xs:integer"/>
    <xs:element name="BYUSER" type="xs:integer"/>
    <xs:element name="READY">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="LOOKFOR-RESOURCE"/>
				<xs:element ref="USER-CHOOSE-RESOURCE"/>
				<xs:element ref="USER-WAITING"/>
                <xs:element ref="WAITING"/>
                <xs:element ref="TRANSFERING"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="USER-CHOOSE-RESOURCE" type="xs:integer"/>
	<xs:element name="USER-WAITING" type="xs:integer"/>
    <xs:element name="LOOKFOR-RESOURCE" type="xs:integer"/>
    <xs:element name="WAITING" type="xs:integer"/>
    <xs:element name="TRANSFERING" type="xs:integer"/>
    <xs:element name="PAUSED" type="xs:integer"/>
    <xs:element name="RUNNING">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="STAGE-IN"/>
                <xs:element ref="MIGRATING"/>
                <xs:element ref="ON-RESOURCE"/>
                <xs:element ref="HELD"/>
                <xs:element ref="STAGE-OUT"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="STAGE-IN" type="xs:integer"/>
    <xs:element name="MIGRATING" type="xs:integer"/>
    <xs:element name="ON-RESOURCE">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TIME-IN"/>
                <xs:element ref="TIME-OUT"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="TIME-IN" type="xs:integer"/>
    <xs:element name="TIME-OUT" type="xs:integer"/>
    <xs:element name="HELD" type="xs:integer"/>
    <xs:element name="STAGE-OUT" type="xs:integer"/>
    <xs:element name="CANCELLED" type="xs:integer"/>
    <xs:element name="FINISHED">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="COMPLETED"/>
                <xs:element ref="SKIPPED"/>
                <xs:element ref="STOPPED"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="COMPLETED">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="SUCCESS"/>
                <xs:element ref="WARNING"/>
                <xs:element ref="FAILED"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="SUCCESS" type="xs:integer"/>
    <xs:element name="WARNING" type="xs:integer"/>
    <xs:element name="SKIPPED" type="xs:integer"/>
    <xs:element name="STOPPED" type="xs:integer"/>
    <xs:element name="FAILED" type="xs:integer"/>
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xmls/tlosSWReports10.xml
<rep:reportAll xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:rep="http://www.likyateknoloji.com/XML_report_types"
	xsi:schemaLocation="http://www.likyateknoloji.com/XML_report_types ../xsds/tlosSWReports_v_1_0.xsd">
	<rep:stateReport>
		<rep:report xmlns="http://www.likyateknoloji.com/XML_report_types"
			id="9" jsId="0" planId="0" scope="job" LSIDateTime="2012-05-09T19:19:49.765+03:00">
			<rep:PENDING>
				<rep:CREATED>
					<rep:DEVELOPMENT>0</rep:DEVELOPMENT>
					<rep:TEST>0</rep:TEST>
                    <rep:REQUEST>0</rep:REQUEST>
					<rep:DEPLOYED>0</rep:DEPLOYED>
				</rep:CREATED>
				<rep:DEACTIVATED>0</rep:DEACTIVATED>
				<rep:VALIDATED>0</rep:VALIDATED>
				<rep:IDLED>
					<rep:BYTIME>0</rep:BYTIME>
					<rep:BYUSER>0</rep:BYUSER>
				</rep:IDLED>
				<rep:READY>
					<rep:LOOKFOR-RESOURCE>0</rep:LOOKFOR-RESOURCE>
					<rep:USER-CHOOSE-RESOURCE>0</rep:USER-CHOOSE-RESOURCE>
					<rep:USER-WAITING>0</rep:USER-WAITING>
					<rep:WAITING>0</rep:WAITING>
					<rep:TRANSFERING>0</rep:TRANSFERING>
				</rep:READY>
				<rep:PAUSED>0</rep:PAUSED>
			</rep:PENDING>
			<rep:RUNNING>
				<rep:STAGE-IN>0</rep:STAGE-IN>
				<rep:MIGRATING>0</rep:MIGRATING>
				<rep:ON-RESOURCE>
					<rep:TIME-IN>0</rep:TIME-IN>
					<rep:TIME-OUT>0</rep:TIME-OUT>
				</rep:ON-RESOURCE>
				<rep:HELD>0</rep:HELD>
				<rep:STAGE-OUT>0</rep:STAGE-OUT>
			</rep:RUNNING>
			<rep:FAILED>0</rep:FAILED>
			<rep:CANCELLED>0</rep:CANCELLED>
			<rep:FINISHED>
				<rep:COMPLETED>
					<rep:SUCCESS>0</rep:SUCCESS>
					<rep:WARNING>0</rep:WARNING>
					<rep:FAILED>0</rep:FAILED>
				</rep:COMPLETED>
				<rep:SKIPPED>0</rep:SKIPPED>
				<rep:STOPPED>0</rep:STOPPED>
			</rep:FINISHED>
		</rep:report>
	</rep:stateReport>
</rep:reportAll>
