=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWNrpe_v_1_0.xsd
<!-- Created for the TLOSSW Scheduler http://www.likyateknoloji.com -->
<xs:schema xmlns="http://www.likyateknoloji.com/XML_nrpe_types" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   targetNamespace="http://www.likyateknoloji.com/XML_nrpe_types" elementFormDefault="qualified">
	
    <xs:element name="NrpeData">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="nrpeCall" minOccurs="0" maxOccurs="unbounded"/>
           </xs:sequence>
       </xs:complexType>
    </xs:element>
    
    <xs:element name="nrpeCall">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="message" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="entry-name" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="port" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="os" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="message">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="response" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="time" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <!-- xs:element name="response">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="responseValue"/>
            </xs:sequence>
            <xs:attribute name="command" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
   	<xs:simpleType name="responseValue">
    	<xs:restriction base="xs:string"/>
	</xs:simpleType-->
	
	<xs:element name="response">
	    <xs:complexType>
	        <xs:attribute name="command" type="xs:string"/>
	        <xs:attribute name="value" type="xs:string"/>	        
	    </xs:complexType>
	</xs:element>

	<!-- xs:element name="response">
	    <xs:complexType>
	        <xs:attribute name="command"
	                type="xs:string"/>
	    </xs:complexType>
	</xs:element-->

	<!-- xs:complexType name="response">
	  <xs:simpleContent>
		<xs:extension base="responseValueType">
		  <xs:attribute name="command">
			<xs:simpleType>
			  <xs:restriction base="xs:string"/>
			</xs:simpleType>
		  </xs:attribute>
		</xs:extension>
	  </xs:simpleContent>
	</xs:complexType>
    
   	<xs:simpleType name="responseValueType">
    	<xs:restriction base="xs:string"/>
	</xs:simpleType-->
	
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xml/tlosSWNrpeData10.xml
<nrp:NrpeData xmlns:nrp="http://www.likyateknoloji.com/XML_nrpe_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.likyateknoloji.com/XML_nrpe_types xmldb:exist:///db/TLOSSW/xsds/tlosSWNrpe_v_1_0.xsd">
    <nrpeCall xmlns="http://www.likyateknoloji.com/XML_nrpe_types" entry-name="sahin-laptop" port="5666" os="Windows">
        <message time="2011-08-25T09:32:35+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=5%;80;90; '5m'=17%;80;90; '1m'=18%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.66G|'physical memory %'=33%;80;90; 'physical memory'=2.65G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:32:41+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=6%;80;90; '5m'=18%;80;90; '1m'=22%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.74G|'physical memory %'=34%;80;90; 'physical memory'=2.73G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:32:46+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=6%;80;90; '5m'=18%;80;90; '1m'=23%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.81G|'physical memory %'=35%;80;90; 'physical memory'=2.81G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:32:52+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=6%;80;90; '5m'=18%;80;90; '1m'=23%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.79G|'physical memory %'=34%;80;90; 'physical memory'=2.78G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:32:57+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=6%;80;90; '5m'=18%;80;90; '1m'=23%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.78G|'physical memory %'=34%;80;90; 'physical memory'=2.78G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:03+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=6%;80;90; '5m'=19%;80;90; '1m'=22%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:08+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=6%;80;90; '5m'=19%;80;90; '1m'=24%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.83G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:13+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=6%;80;90; '5m'=19%;80;90; '1m'=24%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:19+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=7%;80;90; '5m'=19%;80;90; '1m'=23%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:24+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=7%;80;90; '5m'=19%;80;90; '1m'=24%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:30+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=7%;80;90; '5m'=19%;80;90; '1m'=24%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:36+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=7%;80;90; '5m'=19%;80;90; '1m'=22%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:41+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=7%;80;90; '5m'=18%;80;90; '1m'=17%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:46+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=7%;80;90; '5m'=18%;80;90; '1m'=15%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.8G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:52+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=7%;80;90; '5m'=19%;80;90; '1m'=14%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:33:57+0300">
            <response command="alias_cpu" value="OK CPU Load ok.|'15m'=7%;80;90; '5m'=19%;80;90; '1m'=14%;80;90; "/>
            <response command="alias_disk" value="WARNING: C:\: 54.2G, D:\: Total: 108G - Used: 92.4G (85%) - Free: 15.8G (15%) &lt; warning|'C:\ %'=31%;20;10; 'C:\'=54.18G;15.60;7.80;0;78.02; 'D:\ %'=15%;20;10; 'D:\'=92.42G;21.63;10.81;0;108.18; "/>
            <response command="alias_mem" value="OK: physical memory: 2.84G|'physical memory %'=35%;80;90; 'physical memory'=2.83G;6.39;7.19;0;7.99; "/>
        </message>
        <message time="2011-08-25T09:34:03+0300">
