=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWState_v_1_0.xsd
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<xs:schema xmlns="http://www.likyateknoloji.com/state-types" xmlns:state-types="http://www.likyateknoloji.com/state-types" xmlns:jsdl="http://schemas.ggf.org/jsdl/2005/11/jsdl" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.likyateknoloji.com/state-types" elementFormDefault="qualified">
    <xs:import namespace="http://schemas.ggf.org/jsdl/2005/11/jsdl" schemaLocation="jsdl.2005_11.xsd"/>
    
    <xs:element name="StateName">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="PENDING"/>
                <xs:enumeration value="RUNNING"/>
                <xs:enumeration value="CANCELLED"/>
                <xs:enumeration value="FAILED"/>
                <xs:enumeration value="FINISHED"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Code">
        <xs:simpleType>
            <xs:restriction base="xs:int"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Desc">
        <xs:simpleType>
            <xs:restriction base="xs:string"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Name">
        <xs:simpleType>
            <xs:restriction base="xs:string"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="ReturnCode">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="state-types:Code"/>
                <xs:element ref="state-types:Desc"/>
            </xs:sequence>
            <xs:attribute name="cdId" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="ReturnCodeList">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="state-types:ReturnCode" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="osType" use="required">
                <xs:simpleType>
                    <xs:restriction base="jsdl:OperatingSystemTypeEnumeration"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="rclId" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="StatusName">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="SUCCESS"/>
                <xs:enumeration value="WARNING"/>
                <xs:enumeration value="FAILED"/>
                <xs:enumeration value="LOOKFOR-RESOURCE"/>
                <xs:enumeration value="WAITING"/>
                <xs:enumeration value="TRANSFERING"/>
                <xs:enumeration value="TIME-IN"/>
                <xs:enumeration value="TIME-OUT"/>
                <xs:enumeration value="USER-CHOOSE-RESOURCE"/>
				<xs:enumeration value="USER-WAITING"/>
                <xs:enumeration value="BYTIME"/>
                <xs:enumeration value="BYUSER"/>
                <xs:enumeration value="BYEVENT"/>
                <xs:enumeration value="DEVELOPMENT"/>
                <xs:enumeration value="TEST"/>
                <xs:enumeration value="REQUEST"/>
                <xs:enumeration value="DEPLOYED"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:complexType name="Status">
        <xs:sequence>
            <xs:element ref="state-types:StatusName"/>
            <xs:element ref="state-types:Desc"/>
            <xs:element ref="state-types:ReturnCodeList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="stsId" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="SubstateName">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="CREATED"/>
                <xs:enumeration value="DEACTIVATED"/>
                <xs:enumeration value="DEPLOYMENT"/>
                <xs:enumeration value="VALIDATED"/>
                <xs:enumeration value="IDLED"/>
                <xs:enumeration value="READY"/>
                <xs:enumeration value="PAUSED"/>
                <xs:enumeration value="STAGE-IN"/>
                <xs:enumeration value="STAGE-OUT"/>
                <xs:enumeration value="MIGRATING"/>
                <xs:enumeration value="HELD"/>
                <xs:enumeration value="ON-RESOURCE"/>
                <xs:enumeration value="COMPLETED"/>
                <xs:enumeration value="STOPPED"/>
                <xs:enumeration value="SKIPPED"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Substate">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="state-types:SubstateName"/>
                <xs:element ref="state-types:Code"/>
                <xs:element ref="state-types:Desc"/>
                <xs:element name="SubStateStatuses" type="state-types:Status" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="substId" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="State">
        <xs:sequence>
            <xs:element ref="state-types:StateName"/>
            <xs:element ref="state-types:Code"/>
            <xs:element ref="state-types:Desc"/>
            <xs:element ref="state-types:Substate" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="stId" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="jsState">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="state-types:StateName" minOccurs="0"/>
                <xs:element ref="state-types:SubstateName" minOccurs="0"/>
                <xs:element ref="state-types:StatusName" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jsDependencyRule">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="state-types:StateName"/>
                <xs:element ref="state-types:SubstateName" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="state-types:StatusName" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="LiveStateInfo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="state-types:StateName"/>
                <xs:element ref="state-types:SubstateName" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="state-types:StatusName" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="state-types:ReturnCode" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="LSIDateTime" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="userId" use="optional" default="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="LiveStateInfos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="state-types:LiveStateInfo" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ScenarioStatusList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ScenarioStatus" type="state-types:Status" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="UniqueScenarioStatus">
            <xs:selector xpath="state-types:ScenarioStatus"/>
            <xs:field xpath="state-types:StatusName"/>
        </xs:unique>
        <xs:unique name="UniqueScenarioStatusCodes">
            <xs:selector xpath="state-types:ScenarioStatus/state-types:ReturnCodeList/state-types:ReturnCode"/>
            <xs:field xpath="state-types:Code"/>
        </xs:unique>
    </xs:element>
    <xs:element name="JobStatusList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="JobStatus" type="state-types:Status" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="UniqueJobStatus">
            <xs:selector xpath="state-types:JobStatus"/>
            <xs:field xpath="state-types:StatusName"/>
        </xs:unique>
        <xs:unique name="UniqueJobStatusCodes">
            <xs:selector xpath="state-types:JobStatus/state-types:ReturnCodeList/state-types:ReturnCode"/>
            <xs:field xpath="state-types:Code"/>
        </xs:unique>
    </xs:element>
    <xs:element name="GlobalStateDefinition">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GlobalState" type="state-types:State" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="UniqueGlobalState">
            <xs:selector xpath="state-types:GlobalState"/>
            <xs:field xpath="state-types:StateName"/>
            <xs:field xpath="state-types:SubstateName"/>
        </xs:unique>
        <xs:unique name="UniqueGlobalSubState">
            <xs:selector xpath="state-types:GlobalState/state-types:Substate"/>
            <xs:field xpath="state-types:SubstateName"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSWAgentTester/globalStates.xml
<state-types:GlobalStateDefinition
	xmlns:state-types="http://www.likyateknoloji.com/state-types"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.likyateknoloji.com/state-types xmldb:exist:///db/TLOSSW/xsds/tlosSWState_v_1_0.xsd">
	<state-types:GlobalState stId="1">
		<state-types:StateName>PENDING</state-types:StateName>
		<state-types:Code>1</state-types:Code>
		<state-types:Desc>job's state before the running state</state-types:Desc>
		<state-types:Substate substId="1">
			<state-types:SubstateName>CREATED</state-types:SubstateName>
			<state-types:Code>1</state-types:Code>
			<state-types:Desc>job created in database</state-types:Desc>
		</state-types:Substate>
		<state-types:Substate substId="2">
			<state-types:SubstateName>VALIDATED</state-types:SubstateName>
			<state-types:Code>2</state-types:Code>
			<state-types:Desc>job is validated</state-types:Desc>
		</state-types:Substate>
		<state-types:Substate substId="3">
			<state-types:SubstateName>IDLED</state-types:SubstateName>
			<state-types:Code>3</state-types:Code>
			<state-types:Desc>job is idled</state-types:Desc>
		</state-types:Substate>
		<state-types:Substate substId="4">
			<state-types:SubstateName>READY</state-types:SubstateName>
			<state-types:Code>4</state-types:Code>
			<state-types:Desc>job is ready</state-types:Desc>
			<state-types:SubStateStatuses stsId="1">
				<state-types:StatusName>LOOKFOR-RESOURCE</state-types:StatusName>
				<state-types:Desc>looking for an appropriate resource for the job</state-types:Desc>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="2">
				<state-types:StatusName>WAITING</state-types:StatusName>
				<state-types:Desc>waiting for the right time and other conditions</state-types:Desc>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="3">
				<state-types:StatusName>TRANSFERING</state-types:StatusName>
				<state-types:Desc>job is transferring to the choisen resource</state-types:Desc>
			</state-types:SubStateStatuses>
		</state-types:Substate>
		<state-types:Substate substId="5">
			<state-types:SubstateName>PAUSED</state-types:SubstateName>
			<state-types:Code>5</state-types:Code>
			<state-types:Desc>job is paused</state-types:Desc>
		</state-types:Substate>
	</state-types:GlobalState>
	<state-types:GlobalState stId="2">
		<state-types:StateName>RUNNING</state-types:StateName>
		<state-types:Code>2</state-types:Code>
		<state-types:Desc>job is working</state-types:Desc>
		<state-types:Substate substId="1">
			<state-types:SubstateName>STAGE-IN</state-types:SubstateName>
			<state-types:Code>1</state-types:Code>
			<state-types:Desc>Move files for the run if it needs</state-types:Desc>
			<state-types:SubStateStatuses stsId="1">
				<state-types:StatusName>TIME-IN</state-types:StatusName>
				<state-types:Desc>The job is in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="2">
				<state-types:StatusName>TIME-OUT</state-types:StatusName>
				<state-types:Desc>The job is not in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
		</state-types:Substate>
		<state-types:Substate substId="2">
			<state-types:SubstateName>ON-RESOURCE</state-types:SubstateName>
			<state-types:Code>2</state-types:Code>
			<state-types:Desc>job is running on its chosen resource</state-types:Desc>
			<state-types:SubStateStatuses stsId="1">
				<state-types:StatusName>TIME-IN</state-types:StatusName>
				<state-types:Desc>The job is in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="2">
				<state-types:StatusName>TIME-OUT</state-types:StatusName>
				<state-types:Desc>The job is not in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
		</state-types:Substate>
		<state-types:Substate substId="3">
			<state-types:SubstateName>MIGRATING</state-types:SubstateName>
			<state-types:Code>3</state-types:Code>
			<state-types:Desc>job is being migrated to a different resource</state-types:Desc>
			<state-types:SubStateStatuses stsId="1">
				<state-types:StatusName>TIME-IN</state-types:StatusName>
				<state-types:Desc>The job is in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="2">
				<state-types:StatusName>TIME-OUT</state-types:StatusName>
				<state-types:Desc>The job is not in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
		</state-types:Substate>
		<state-types:Substate substId="4">
			<state-types:SubstateName>HELD</state-types:SubstateName>
			<state-types:Code>4</state-types:Code>
			<state-types:Desc>job is being held by the user</state-types:Desc>
			<state-types:SubStateStatuses stsId="1">
				<state-types:StatusName>TIME-IN</state-types:StatusName>
				<state-types:Desc>The job is in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="2">
				<state-types:StatusName>TIME-OUT</state-types:StatusName>
				<state-types:Desc>The job is not in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
		</state-types:Substate>
		<state-types:Substate substId="5">
			<state-types:SubstateName>STAGE-OUT</state-types:SubstateName>
			<state-types:Code>5</state-types:Code>
			<state-types:Desc>Move resulted files for the run if it needs</state-types:Desc>
			<state-types:SubStateStatuses stsId="1">
				<state-types:StatusName>TIME-IN</state-types:StatusName>
				<state-types:Desc>The job is in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="2">
				<state-types:StatusName>TIME-OUT</state-types:StatusName>
				<state-types:Desc>The job is not in its time window</state-types:Desc>
			</state-types:SubStateStatuses>
		</state-types:Substate>
	</state-types:GlobalState>
	<state-types:GlobalState stId="3">
		<state-types:StateName>FINISHED</state-types:StateName>
		<state-types:Code>3</state-types:Code>
		<state-types:Desc>job is finished</state-types:Desc>
		<state-types:Substate substId="1">
			<state-types:SubstateName>COMPLETED</state-types:SubstateName>
			<state-types:Code>1</state-types:Code>
			<state-types:Desc>job is completed</state-types:Desc>
			<state-types:SubStateStatuses stsId="1">
				<state-types:StatusName>SUCCESS</state-types:StatusName>
				<state-types:Desc>job is completed with success</state-types:Desc>
				<state-types:ReturnCodeList osType="Unix"
					rclId="1">
					<state-types:ReturnCode cdId="1">
						<state-types:Code>0</state-types:Code>
						<state-types:Desc>job's status OS return code</state-types:Desc>
					</state-types:ReturnCode>
				</state-types:ReturnCodeList>
				<state-types:ReturnCodeList osType="Windows"
					rclId="2">
					<state-types:ReturnCode cdId="2">
						<state-types:Code>0</state-types:Code>
						<state-types:Desc>job's status OS return code</state-types:Desc>
					</state-types:ReturnCode>
				</state-types:ReturnCodeList>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="2">
				<state-types:StatusName>FAILED</state-types:StatusName>
				<state-types:Desc>job is completed with a problem, therefore it is
					failed</state-types:Desc>
				<state-types:ReturnCodeList osType="Unix"
					rclId="1">
					<state-types:ReturnCode cdId="1">
						<state-types:Code>1</state-types:Code>
						<state-types:Desc>state-types:Desc</state-types:Desc>
					</state-types:ReturnCode>
					<state-types:ReturnCode cdId="2">
						<state-types:Code>2</state-types:Code>
						<state-types:Desc>state-types:Desc</state-types:Desc>
					</state-types:ReturnCode>
					<state-types:ReturnCode cdId="3">
						<state-types:Code>3</state-types:Code>
						<state-types:Desc>state-types:Desc</state-types:Desc>
					</state-types:ReturnCode>
				</state-types:ReturnCodeList>
				<state-types:ReturnCodeList osType="Windows"
					rclId="2">
					<state-types:ReturnCode cdId="1">
						<state-types:Code>1</state-types:Code>
						<state-types:Desc>state-types:Desc</state-types:Desc>
					</state-types:ReturnCode>
					<state-types:ReturnCode cdId="2">
						<state-types:Code>2</state-types:Code>
						<state-types:Desc>state-types:Desc</state-types:Desc>
					</state-types:ReturnCode>
					<state-types:ReturnCode cdId="3">
						<state-types:Code>3</state-types:Code>
						<state-types:Desc>state-types:Desc</state-types:Desc>
					</state-types:ReturnCode>
				</state-types:ReturnCodeList>
			</state-types:SubStateStatuses>
			<state-types:SubStateStatuses stsId="3">
				<state-types:StatusName>WARNING</state-types:StatusName>
				<state-types:Desc>job is completed with a number of warnings</state-types:Desc>
				<state-types:ReturnCodeList osType="Unix"
					rclId="1">
					<state-types:ReturnCode cdId="1">
						<state-types:Code>4</state-types:Code>
						<state-types:Desc>state-types:Desc</state-types:Desc>
					</state-types:ReturnCode>
				</state-types:ReturnCodeList>
				<state-types:ReturnCodeList osType="Windows"
					rclId="2">
					<state-types:ReturnCode cdId="2">
						<state-types:Code>4</state-types:Code>
						<state-types:Desc>state-types:Desc</state-types:Desc>
					</state-types:ReturnCode>
				</state-types:ReturnCodeList>
			</state-types:SubStateStatuses>
		</state-types:Substate>
		<state-types:Substate substId="2">
			<state-types:SubstateName>SKIPPED</state-types:SubstateName>
			<state-types:Code>1</state-types:Code>
			<state-types:Desc>job is skipped</state-types:Desc>
		</state-types:Substate>
		<state-types:Substate substId="3">
			<state-types:SubstateName>STOPPED</state-types:SubstateName>
			<state-types:Code>1</state-types:Code>
			<state-types:Desc>job is stopped</state-types:Desc>
		</state-types:Substate>
	</state-types:GlobalState>
	<state-types:GlobalState stId="4">
		<state-types:StateName>FAILED</state-types:StateName>
		<state-types:Code>4</state-types:Code>
