=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWPermission_v_1_0.xsd
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<xs:schema xmlns="http://www.likyateknoloji.com/XML_permission_types" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:lt="http://www.likyateknoloji.com/XML_common_types" targetNamespace="http://www.likyateknoloji.com/XML_permission_types" elementFormDefault="qualified">
    <xs:import namespace="http://www.likyateknoloji.com/XML_common_types" schemaLocation="tlosSWOrtak_v_1_0.xsd"/>
    <xs:element name="permissions">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="permission"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="permission">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="roles"/>
                <xs:element ref="resource"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="type" type="xs:NCName"/>
    <xs:element name="roles">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="role"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="role" type="xs:NCName"/>
    <xs:element name="resource">
        <xs:complexType mixed="true">
            <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xmls/tlosSWPermission10.xml
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<per:permissions xmlns:com="http://www.likyateknoloji.com/XML_common_types" xmlns:per="http://www.likyateknoloji.com/XML_permission_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.likyateknoloji.com/XML_permission_types ../xsds/tlosSWPermission_v_1_0.xsd">
    <per:permission id="1">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="panel">Live</per:resource>
    </per:permission>
    <per:permission id="2">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="panel">WorkSpace</per:resource>
    </per:permission>
    <per:permission id="3">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="panel">Reports</per:resource>
    </per:permission>
    <per:permission id="4">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="panel">Management</per:resource>
    </per:permission>
    <per:permission id="5">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">StopScenarioNormally</per:resource>
    </per:permission>
    <per:permission id="6">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">StopScenarioForced</per:resource>
    </per:permission>
    <per:permission id="7">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">PauseScenario</per:resource>
    </per:permission>
    <per:permission id="8">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">ResumeScenario</per:resource>
    </per:permission>
    <per:permission id="9">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">StartScenario</per:resource>
    </per:permission>
    <per:permission id="10">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="combo">JobFilter</per:resource>
    </per:permission>
    <per:permission id="11">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">RetryJob</per:resource>
    </per:permission>
    <per:permission id="12">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">SetSuccessJob</per:resource>
    </per:permission>
    <per:permission id="13">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">SkipJob</per:resource>
    </per:permission>
    <per:permission id="14">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">StopJob</per:resource>
    </per:permission>
    <per:permission id="15">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">PauseJob</per:resource>
    </per:permission>
    <per:permission id="16">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">ResumeJob</per:resource>
    </per:permission>
    <per:permission id="17">
        <per:roles>
            <per:role>ADMIN</per:role>
        </per:roles>
        <per:resource type="button">StartJob</per:resource>
    </per:permission>
    <per:permission id="18">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="button">LogOut</per:resource>
    </per:permission>
    <per:permission id="20">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="tree">TlosEnterprise</per:resource>
    </per:permission>
    <per:permission id="21">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="treeNode">DailyJobs</per:resource>
    </per:permission>
    <per:permission id="22">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="tree">WorkSpace</per:resource>
    </per:permission>
    <per:permission id="22">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="tree">WorkSpace</per:resource>
    </per:permission>
    <per:permission id="23">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="treeNode">CalendarOperations</per:resource>
    </per:permission>
    <per:permission id="24">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="treeNode">ScenarioDefinition</per:resource>
    </per:permission>
    <per:permission id="25">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
            <per:role>NORMALUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarSearch</per:resource>
    </per:permission>
    <per:permission id="26">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarClear</per:resource>
    </per:permission>
    <per:permission id="27">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarAdd</per:resource>
    </per:permission>
    <per:permission id="28">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarEdit</per:resource>
    </per:permission>
    <per:permission id="29">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarDelete</per:resource>
    </per:permission>
    <per:permission id="30">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarSave</per:resource>
    </per:permission>
    <per:permission id="67">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarUpdate</per:resource>
    </per:permission>
    <per:permission id="31">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarBack</per:resource>
    </per:permission>
    <per:permission id="32">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">CalendarDefinitionClean</per:resource>
    </per:permission>
    <per:permission id="34">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="tree">ScenarioTree</per:resource>
    </per:permission>
    <per:permission id="35">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="menu">NewScenario</per:resource>
    </per:permission>
    <per:permission id="36">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="menu">NewJob</per:resource>
    </per:permission>
    <per:permission id="37">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">NewScenarioContinue</per:resource>
    </per:permission>
    <per:permission id="73">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">ScenarioDelete</per:resource>
    </per:permission>
    <per:permission id="68">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">ScenarioUpdate</per:resource>
    </per:permission>
    <per:permission id="38">
        <per:roles>
            <per:role>ADMIN</per:role>
            <per:role>SUPERUSER</per:role>
        </per:roles>
        <per:resource type="button">NewScenarioClear</per:resource>
    </per:permission>
    <per:permission id="39">
        <per:roles>
