=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWNrpeResult_v_1_0.xsd
<!-- Created for the TLOSSW Scheduler http://www.likyateknoloji.com -->
<xs:schema xmlns="http://www.likyateknoloji.com/XML_nrpe_results" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:lt="http://www.likyateknoloji.com/XML_common_types" targetNamespace="http://www.likyateknoloji.com/XML_nrpe_results" elementFormDefault="qualified">
    <xs:import namespace="http://www.likyateknoloji.com/XML_common_types" schemaLocation="tlosSWOrtak_v_1_0.xsd"/>
    <xs:element name="NrpeData">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nrpeCall" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nrpeCall">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="message" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="entry-name" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="port" use="required" type="lt:portType"/>
            <xs:attribute name="os" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="message">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="response" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="time" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
<!--
    <xs:element name="response">
        <xs:complexType>
            <xs:attribute name="command" type="xs:string"/>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
-->

	<xs:element name="response">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="cpu" minOccurs="1" maxOccurs="3"/>
				<xs:element ref="disk" minOccurs="1" maxOccurs="2"/>
				<xs:element ref="mem" minOccurs="1" maxOccurs="2"/>
            </xs:choice>
            <xs:attribute name="command" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="alias_cpu"/>
					  <xs:enumeration value="alias_disk"/>
					  <xs:enumeration value="alias_mem"/>
					  <xs:enumeration value="check_moad"/>
					  <xs:enumeration value="check_disk"/>
					  <xs:enumeration value="check_mem"/>			  
					</xs:restriction>	  
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="cpuKullanimType">
      <xs:simpleContent>
       <xs:extension base="xs:nonNegativeInteger">
            <xs:attribute name="timein" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="1"/>
					  <xs:enumeration value="5"/>
					  <xs:enumeration value="15"/>		  
					</xs:restriction>  
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="birim" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="%"/>
					  <xs:enumeration value="G"/>
					  <xs:enumeration value="M"/>
					  <xs:enumeration value="K"/>
					  <xs:enumeration value="GB"/>
					  <xs:enumeration value="MB"/>
					  <xs:enumeration value="KB"/>
					  <xs:enumeration value="B"/>			  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
       </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="memdiskKullanimType">
      <xs:simpleContent>
       <xs:extension base="xs:float">
            <xs:attribute name="for" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="used"/>
					  <xs:enumeration value="free"/>			  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="birim" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="%"/>
					  <xs:enumeration value="G"/>
					  <xs:enumeration value="M"/>
					  <xs:enumeration value="K"/>
					  <xs:enumeration value="GB"/>
					  <xs:enumeration value="MB"/>
					  <xs:enumeration value="KB"/>
					  <xs:enumeration value="B"/>			  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
       </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
    
    <xs:element name="cpu" type="cpuKullanimType"/>
    <xs:element name="mem" type="memdiskKullanimType"/>
    <xs:element name="disk" type="memdiskKullanimType"/>
<!-- 
    <xs:element name="cpu">
        <xs:complexType>
            <xs:attribute name="timein" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="1"/>
					  <xs:enumeration value="5"/>
					  <xs:enumeration value="15"/>		  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="birim" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="%"/>
					  <xs:enumeration value="G"/>
					  <xs:enumeration value="M"/>
					  <xs:enumeration value="K"/>
					  <xs:enumeration value="B"/>			  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="disk">
        <xs:complexType>
            <xs:attribute name="for" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="used"/>
					  <xs:enumeration value="free"/>			  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="birim" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="%"/>
					  <xs:enumeration value="G"/>
					  <xs:enumeration value="M"/>
					  <xs:enumeration value="K"/>
					  <xs:enumeration value="B"/>			  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
  <xs:element name="mem">
        <xs:complexType>
            <xs:attribute name="for" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="used"/>
					  <xs:enumeration value="free"/>			  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="birim" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
					  <xs:enumeration value="%"/>
					  <xs:enumeration value="G"/>
					  <xs:enumeration value="M"/>
					  <xs:enumeration value="K"/>
					  <xs:enumeration value="B"/>			  
					</xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
     -->
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xml/tlosSWNrpeResult_v_1_0.xml
<nrp:NrpeData xmlns:nrp="http://www.likyateknoloji.com/XML_nrpe_results"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.likyateknoloji.com/XML_nrpe_results ../xsds/tlosSWNrpeResult_v_1_0.xsd">
	<nrp:nrpeCall entry-name="sahin-laptop" port="5666" os="windows">
		<nrp:message time="2012-02-21T01:01:01+0300">
			<nrp:response command="alias_cpu">
				<nrp:cpu timein="1" birim="%">9</nrp:cpu>
				<nrp:cpu timein="5" birim="%">8</nrp:cpu>
				<nrp:cpu timein="15" birim="%">12</nrp:cpu>
			</nrp:response>
			<nrp:response command="alias_disk">
				<nrp:disk forWhat="used" birim="G">53.19</nrp:disk>
				<nrp:disk forWhat="free" birim="G">24.83</nrp:disk>
			</nrp:response>
			<nrp:response command="alias_mem">
				<nrp:mem forWhat="used" birim="G">3.32</nrp:mem>
				<nrp:mem forWhat="free" birim="G">4.67</nrp:mem>
			</nrp:response>
		</nrp:message>
		<nrp:message time="2012-02-21T01:01:31+0300">
			<nrp:response command="alias_cpu">
				<nrp:cpu timein="1" birim="%">9</nrp:cpu>
				<nrp:cpu timein="5" birim="%">8</nrp:cpu>
				<nrp:cpu timein="15" birim="%">13</nrp:cpu>
			</nrp:response>
			<nrp:response command="alias_disk">
				<nrp:disk forWhat="used" birim="G">53.19</nrp:disk>
				<nrp:disk forWhat="free" birim="G">24.83</nrp:disk>
			</nrp:response>
			<nrp:response command="alias_mem">
				<nrp:mem forWhat="used" birim="G">3.31</nrp:mem>
				<nrp:mem forWhat="free" birim="G">4.68</nrp:mem>
			</nrp:response>
		</nrp:message>
	</nrp:nrpeCall>
	<nrp:nrpeCall entry-name="laptop-hakan" port="5666" os="windows">
		<nrp:message time="2012-02-21T01:01:01+0300">
			<nrp:response command="alias_cpu">
				<nrp:cpu timein="1" birim="%">10</nrp:cpu>
				<nrp:cpu timein="5" birim="%">8</nrp:cpu>
				<nrp:cpu timein="15" birim="%">13</nrp:cpu>
			</nrp:response>
			<nrp:response command="alias_disk">
				<nrp:disk forWhat="used" birim="G">53.19</nrp:disk>
				<nrp:disk forWhat="free" birim="G">24.83</nrp:disk>
			</nrp:response>
			<nrp:response command="alias_mem">
				<nrp:mem forWhat="used" birim="G">3.31</nrp:mem>
				<nrp:mem forWhat="free" birim="G">4.68</nrp:mem>
			</nrp:response>
		</nrp:message>
		<nrp:message time="2012-02-21T01:01:31+0300">
			<nrp:response command="alias_cpu">
				<nrp:cpu timein="1" birim="%">11</nrp:cpu>
				<nrp:cpu timein="5" birim="%">8</nrp:cpu>
				<nrp:cpu timein="15" birim="%">13</nrp:cpu>
			</nrp:response>
			<nrp:response command="alias_disk">
				<nrp:disk forWhat="used" birim="G">53.19</nrp:disk>
				<nrp:disk forWhat="free" birim="G">24.83</nrp:disk>
			</nrp:response>
			<nrp:response command="alias_mem">
				<nrp:mem forWhat="used" birim="G">3.32</nrp:mem>
				<nrp:mem forWhat="free" birim="G">4.67</nrp:mem>
			</nrp:response>
		</nrp:message>
	</nrp:nrpeCall>
</nrp:NrpeData>
