=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWProgramProvisioning_v_1_0.xsd
<xs:schema xmlns="http://www.likyateknoloji.com/XML_PP_types"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		   xmlns:lt="http://www.likyateknoloji.com/XML_common_types"
           targetNamespace="http://www.likyateknoloji.com/XML_PP_types">
  <xs:import namespace="http://www.likyateknoloji.com/XML_common_types" schemaLocation="tlosSWOrtak_v_1_0.xsd"/>
  <xs:element name="Licenses">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="License"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="License">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="version"/>
        <xs:element ref="StartDate"/>
        <xs:element ref="EndDate"/>
        <xs:element ref="ResourcePool"/>
        <xs:element ref="Type"/>
        <xs:element ref="lt:userId"/>
      </xs:sequence>
      <xs:attribute name="licenseID" use="required" type="xs:nonNegativeInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name" type="xs:string"/>
  <xs:element name="version" type="xs:NMTOKEN"/>
  <xs:element name="StartDate" type="xs:dateTime"/>
  <xs:element name="EndDate" type="xs:dateTime"/>
  <xs:element name="ResourcePool">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Resource"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Resource" type="xs:NCName"/>
  <xs:element name="Type">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="maxUser" type="xs:nonNegativeInteger"/>
          <xs:attribute name="minUser" type="xs:nonNegativeInteger"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xml/tlosSWProgramProvisioning10.xml
<?xml version="1.0"?>
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<pp:Licenses xmlns:com="http://www.likyateknoloji.com/XML_common_types"
	xmlns:pp="http://www.likyateknoloji.com/XML_PP_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.likyateknoloji.com/XML_PP_types ../xsds/tlosSWProgramProvisioning_v_1_0.xsd http://www.likyateknoloji.com/XML_common_types ../xsds/tlosSWOrtak_v_1_0.xsd">
	<pp:License licenseID="1">
		<pp:Name>Tlos SW</pp:Name>
		<pp:version>V1.0</pp:version>
		<pp:StartDate>2011-05-30T09:30:10+02:00</pp:StartDate>
		<pp:EndDate>2015-05-30T09:30:10+02:00</pp:EndDate>
		<pp:ResourcePool>
			<pp:Resource>WINSRVSTD2012</pp:Resource>
			<pp:Resource>sahin-laptop</pp:Resource>
		</pp:ResourcePool>
		<pp:Type>Unlimited</pp:Type>
		<com:userId>1</com:userId>
	</pp:License>
	<pp:License licenseID="2">
		<pp:Name>SAS</pp:Name>
		<pp:version>9.2</pp:version>
		<pp:StartDate>2011-05-30T09:30:10+02:00</pp:StartDate>
		<pp:EndDate>2012-05-30T09:30:10+02:00</pp:EndDate>
		<pp:ResourcePool>
			<pp:Resource>laptop-hakan</pp:Resource>
			<pp:Resource>sahin-laptop</pp:Resource>
		</pp:ResourcePool>
		<pp:Type minUser="1" maxUser="10">Limited</pp:Type>
		<com:userId>1</com:userId>
	</pp:License>
</pp:Licenses>
