=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWAgent_v_1_0.xsd
<xs:schema xmlns="http://www.likyateknoloji.com/XML_agent_types" xmlns:dat="http://www.likyateknoloji.com/XML_data_types" xmlns:lt="http://www.likyateknoloji.com/XML_common_types" xmlns:par="http://www.likyateknoloji.com/XML_parameters_types" xmlns:res="http://www.likyateknoloji.com/resource-extension-defs" xmlns:state-types="http://www.likyateknoloji.com/state-types" xmlns:jsdl="http://schemas.ggf.org/jsdl/2005/11/jsdl" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.likyateknoloji.com/XML_agent_types" elementFormDefault="qualified">
    <xs:import namespace="http://www.likyateknoloji.com/XML_common_types" schemaLocation="tlosSWOrtak_v_1_0.xsd"/>
    <xs:import namespace="http://www.likyateknoloji.com/XML_data_types" schemaLocation="tlosSWData_v_1_0.xsd"/>
    <xs:import namespace="http://schemas.ggf.org/jsdl/2005/11/jsdl" schemaLocation="jsdl.2005_11.xsd"/>
    <xs:import namespace="http://www.likyateknoloji.com/state-types" schemaLocation="tlosSWState_v_1_0.xsd"/>
    <xs:import namespace="http://www.likyateknoloji.com/XML_parameters_types" schemaLocation="tlosSWParameters_v_1_0.xsd"/>
    <xs:import namespace="http://www.likyateknoloji.com/resource-extension-defs" schemaLocation="tlosSW-resource-extension-defs.xsd"/>
    
    <xs:element name="TxMessageTypeEnumeration">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="JOB"/>
                <xs:enumeration value="SCENARIO"/>
                <xs:enumeration value="JOB_STATE"/>
                <xs:enumeration value="SCENARIO_STATE"/>
                <xs:enumeration value="RESULT"/>
                <xs:enumeration value="AlARM"/>
                <xs:enumeration value="REPORT"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="RxMessageTypeEnumeration">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="JOB"/>
                <xs:enumeration value="SCENARIO"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="RxMessageBodyType">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="dat:jobProperties"/>
                <xs:element ref="dat:scenario"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="TxMessageBodyType">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="dat:jobProperties"/>
                <xs:element ref="dat:scenario"/>
                <xs:element ref="state-types:LiveStateInfo"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="RxMessage">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="RxMessageTypeEnumeration"/>
                <xs:element ref="RxMessageBodyType"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="TxMessage">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TxMessageTypeEnumeration"/>
                <xs:element ref="TxMessageBodyType"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

	<!--========================================================================-->
	<!-- COMPLEX TYPES : SWAgent related types -->
    <xs:element name="SWAgents">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="SWAgent" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="SWAgent">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="res:Resource"/>
                <xs:element ref="osType"/>
                <xs:element ref="agentType"/>
                <xs:element ref="nrpePort" minOccurs="0"/>
                <xs:element ref="jmxTlsPort"/>
                <xs:element ref="jmxUser"/>
                <xs:element ref="jmxPassword"/>
                <xs:element ref="inJmxAvailable"/>
                <xs:element ref="outJmxAvailable"/>
                <xs:element ref="jmxAvailable"/>
                <xs:element ref="userStopRequest"/>
                <xs:element ref="nrpeAvailable"/>
                <xs:element ref="lastHeartBeatTime"/>
                <xs:element ref="durationForUnavailability"/>
                <xs:element ref="lastJobTransfer"/>
                <xs:element ref="isPermitted"/>
                <xs:element ref="jobTransferFailureTime"/>
                <xs:element ref="workspacePath"/>
                <xs:element ref="locals" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int"/>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="workspacePath" type="lt:dirType" />

    <xs:element name="ipAddress" type="lt:ipAddressType" />

    <xs:element name="osType">
        <xs:simpleType>
            <xs:restriction base="jsdl:OperatingSystemTypeEnumeration"/>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="agentType">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="agent"/>
                <xs:enumeration value="server"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="inJmxAvailable" type="xs:boolean" default="true"/>
    <xs:element name="outJmxAvailable" type="xs:boolean" default="true"/>
    <xs:element name="jmxAvailable" type="xs:boolean" default="true"/>
    <xs:element name="userStopRequest">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="null"/>
                <xs:enumeration value="normal"/>
                <xs:enumeration value="forced"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="nrpeAvailable" type="xs:boolean" default="true"/>
    
    <xs:element name="nrpePort" type="lt:portType"/>

    <xs:element name="jmxTlsPort" type="lt:portType"/>

    <xs:element name="jmxUser" type="lt:userNameType" />
    
    <xs:element name="jmxPassword" type="lt:passwordType" />
    
    <xs:element name="lastHeartBeatTime" default="0">
        <xs:simpleType>
            <xs:restriction base="xs:long"/>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="durationForUnavailability" default="900">
        <xs:simpleType>
            <xs:restriction base="xs:int"/>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="jobTransferFailureTime" default="0">
        <xs:simpleType>
            <xs:restriction base="xs:long"/>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="lastJobTransfer" type="xs:boolean" default="true"/>
    
    <xs:element name="isPermitted" type="xs:boolean" default="true"/>    
	
    <xs:element name="locals">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="par:parameter"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xmls/tlosSWAgents10.xml
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<agnt:SWAgents xmlns:res="http://www.likyateknoloji.com/resource-extension-defs"
	xmlns:agnt="http://www.likyateknoloji.com/XML_agent_types" xmlns:par="http://www.likyateknoloji.com/XML_parameters_types"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.likyateknoloji.com/XML_agent_types ../xsds/tlosSWAgent_v_1_0.xsd">
	<agnt:SWAgent id="1">
		<res:Resource>WINSRVSTD2012</res:Resource>
		<agnt:osType>Windows</agnt:osType>
		<agnt:agentType>server</agnt:agentType>
		<agnt:nrpePort>5666</agnt:nrpePort>
		<agnt:jmxTlsPort>5570</agnt:jmxTlsPort>
		<agnt:jmxUser>jmxuser</agnt:jmxUser>
		<agnt:jmxPassword>jmxpaswd</agnt:jmxPassword>
		<agnt:inJmxAvailable>true</agnt:inJmxAvailable>
		<agnt:outJmxAvailable>true</agnt:outJmxAvailable>
		<agnt:jmxAvailable>true</agnt:jmxAvailable>
		<agnt:userStopRequest>null</agnt:userStopRequest>
		<agnt:nrpeAvailable>false</agnt:nrpeAvailable>
		<agnt:lastHeartBeatTime>0</agnt:lastHeartBeatTime>
		<agnt:durationForUnavailability>180</agnt:durationForUnavailability>
		<agnt:lastJobTransfer>true</agnt:lastJobTransfer>
		<agnt:isPermitted>true</agnt:isPermitted>
		<agnt:jobTransferFailureTime>0</agnt:jobTransferFailureTime>
		<agnt:workspacePath>D:\user\hakan\TlosSW</agnt:workspacePath>
	</agnt:SWAgent>
	<!-- agnt:SWAgent id="2">
        <res:Resource>laptop-hakan</res:Resource>
        <agnt:osType>Windows</agnt:osType>
        <agnt:agentType>agent</agnt:agentType>
        <agnt:nrpePort>5666</agnt:nrpePort>
        <agnt:jmxTlsPort>5556</agnt:jmxTlsPort>
        <agnt:jmxUser>jmxuser</agnt:jmxUser>
        <agnt:jmxPassword>jmxpaswd</agnt:jmxPassword>
        <agnt:inJmxAvailable>false</agnt:inJmxAvailable>
        <agnt:outJmxAvailable>false</agnt:outJmxAvailable>
        <agnt:jmxAvailable>false</agnt:jmxAvailable>
        <agnt:userStopRequest>null</agnt:userStopRequest>
        <agnt:nrpeAvailable>false</agnt:nrpeAvailable>
        <agnt:lastHeartBeatTime>0</agnt:lastHeartBeatTime>
        <agnt:durationForUnavailability>180</agnt:durationForUnavailability>
        <agnt:lastJobTransfer>true</agnt:lastJobTransfer>
        <agnt:isPermitted>true</agnt:isPermitted>
        <agnt:jobTransferFailureTime>0</agnt:jobTransferFailureTime>
        <agnt:workspacePath>D:\user\hakan\TlosSW</agnt:workspacePath>
    </agnt:SWAgent>
    <agnt:SWAgent id="3">
        <res:Resource>patarafedora</res:Resource>
        <agnt:osType>Unix</agnt:osType>
        <agnt:agentType>agent</agnt:agentType>
        <agnt:nrpePort>5666</agnt:nrpePort>
        <agnt:jmxTlsPort>5685</agnt:jmxTlsPort>
        <agnt:jmxUser>jmxuser</agnt:jmxUser>
        <agnt:jmxPassword>jmxpaswd</agnt:jmxPassword>
        <agnt:inJmxAvailable>false</agnt:inJmxAvailable>
        <agnt:outJmxAvailable>false</agnt:outJmxAvailable>
        <agnt:jmxAvailable>false</agnt:jmxAvailable>
        <agnt:userStopRequest>null</agnt:userStopRequest>
        <agnt:nrpeAvailable>false</agnt:nrpeAvailable>
        <agnt:lastHeartBeatTime>0</agnt:lastHeartBeatTime>
        <agnt:durationForUnavailability>180</agnt:durationForUnavailability>
        <agnt:lastJobTransfer>true</agnt:lastJobTransfer>
        <agnt:isPermitted>true</agnt:isPermitted>
        <agnt:jobTransferFailureTime>0</agnt:jobTransferFailureTime>
        <agnt:workspacePath>D:\user\hakan\TlosSW</agnt:workspacePath>
    </agnt:SWAgent>
    <agnt:SWAgent id="11">
        <res:Resource>laptop-hakan</res:Resource>
        <agnt:osType>Windows</agnt:osType>
        <agnt:agentType>server</agnt:agentType>
        <agnt:nrpePort>5666</agnt:nrpePort>
        <agnt:jmxTlsPort>5555</agnt:jmxTlsPort>
        <agnt:jmxUser>jmxuser</agnt:jmxUser>
        <agnt:jmxPassword>jmxpaswd</agnt:jmxPassword>
        <agnt:inJmxAvailable>true</agnt:inJmxAvailable>
        <agnt:outJmxAvailable>true</agnt:outJmxAvailable>
        <agnt:jmxAvailable>true</agnt:jmxAvailable>
        <agnt:userStopRequest>null</agnt:userStopRequest>
        <agnt:nrpeAvailable>true</agnt:nrpeAvailable>
        <agnt:lastHeartBeatTime>0</agnt:lastHeartBeatTime>
        <agnt:durationForUnavailability>180</agnt:durationForUnavailability>
        <agnt:lastJobTransfer>true</agnt:lastJobTransfer>
        <agnt:isPermitted>true</agnt:isPermitted>
        <agnt:jobTransferFailureTime>0</agnt:jobTransferFailureTime>
        <agnt:workspacePath>D:\user\hakan\TlosSW</agnt:workspacePath>
        <agnt:locals>
            <par:parameter id="91">
                <par:name>JAVAPATH</par:name>
                <par:valueString>C:\Program Files (x86)\Java\jdk1.6.0_21\bin\</par:valueString>
                <par:preValue type="2">C:\Program Files (x86)\Java\jdk1.6.0_21\bin\</par:preValue>
                <par:desc>JAVA PATH</par:desc>
            </par:parameter>
        </agnt:locals>
    </agnt:SWAgent>
    <agnt:SWAgent id="14">
        <res:Resource>nurkan-laptop</res:Resource>
        <agnt:osType>Windows</agnt:osType>
        <agnt:agentType>agent</agnt:agentType>
        <agnt:nrpePort>5666</agnt:nrpePort>
        <agnt:jmxTlsPort>5557</agnt:jmxTlsPort>
        <agnt:jmxUser>jmxuser</agnt:jmxUser>
        <agnt:jmxPassword>jmxpaswd</agnt:jmxPassword>
        <agnt:inJmxAvailable>false</agnt:inJmxAvailable>
        <agnt:outJmxAvailable>false</agnt:outJmxAvailable>
        <agnt:jmxAvailable>false</agnt:jmxAvailable>
        <agnt:userStopRequest>null</agnt:userStopRequest>
        <agnt:nrpeAvailable>false</agnt:nrpeAvailable>
        <agnt:lastHeartBeatTime>0</agnt:lastHeartBeatTime>
        <agnt:durationForUnavailability>180</agnt:durationForUnavailability>
        <agnt:lastJobTransfer>true</agnt:lastJobTransfer>
        <agnt:isPermitted>true</agnt:isPermitted>
        <agnt:jobTransferFailureTime>0</agnt:jobTransferFailureTime>
        <agnt:workspacePath>D:\user\hakan\TlosSW</agnt:workspacePath>
        <agnt:locals>
            <par:parameter id="91">
                <par:name>JAVAPATH</par:name>
                <par:valueString>D:\dev\Java\jdk1.6.0_24\bin\</par:valueString>
                <par:preValue type="2">D:\dev\Java\jdk1.6.0_24\bin\</par:preValue>
                <par:desc>JAVA PATH</par:desc>
            </par:parameter>
        </agnt:locals>
    </agnt:SWAgent>
    <agnt:SWAgent id="15">
        <res:Resource>tlossw-test1</res:Resource>
        <agnt:osType>Windows</agnt:osType>
        <agnt:agentType>agent</agnt:agentType>
        <agnt:nrpePort>5666</agnt:nrpePort>
        <agnt:jmxTlsPort>5557</agnt:jmxTlsPort>
        <agnt:jmxUser>jmxuser</agnt:jmxUser>
        <agnt:jmxPassword>jmxpaswd</agnt:jmxPassword>
        <agnt:inJmxAvailable>false</agnt:inJmxAvailable>
        <agnt:outJmxAvailable>false</agnt:outJmxAvailable>
        <agnt:jmxAvailable>false</agnt:jmxAvailable>
        <agnt:userStopRequest>null</agnt:userStopRequest>
        <agnt:nrpeAvailable>false</agnt:nrpeAvailable>
        <agnt:lastHeartBeatTime>0</agnt:lastHeartBeatTime>
        <agnt:durationForUnavailability>180</agnt:durationForUnavailability>
        <agnt:lastJobTransfer>true</agnt:lastJobTransfer>
        <agnt:isPermitted>true</agnt:isPermitted>
        <agnt:jobTransferFailureTime>0</agnt:jobTransferFailureTime>
        <agnt:workspacePath>D:\user\hakan\TlosSW</agnt:workspacePath>
        <agnt:locals>
            <par:parameter id="91">
                <par:name>JAVAPATH</par:name>
                <par:valueString>D:\dev\Java\jdk1.6.0_21\bin\</par:valueString>
                <par:preValue type="2">D:\dev\Java\jdk1.6.0_21\bin\</par:preValue>
                <par:desc>JAVA PATH</par:desc>
            </par:parameter>
        </agnt:locals>
    </agnt:SWAgent>
    <agnt:SWAgent id="16">
        <res:Resource>tlossw-test2</res:Resource>
        <agnt:osType>Windows</agnt:osType>
        <agnt:agentType>agent</agnt:agentType>
        <agnt:nrpePort>5666</agnt:nrpePort>
        <agnt:jmxTlsPort>3001</agnt:jmxTlsPort>
        <agnt:jmxUser>jmxuser</agnt:jmxUser>
        <agnt:jmxPassword>jmxpaswd</agnt:jmxPassword>
        <agnt:inJmxAvailable>false</agnt:inJmxAvailable>
        <agnt:outJmxAvailable>false</agnt:outJmxAvailable>
        <agnt:jmxAvailable>false</agnt:jmxAvailable>
        <agnt:userStopRequest>null</agnt:userStopRequest>
        <agnt:nrpeAvailable>false</agnt:nrpeAvailable>
        <agnt:lastHeartBeatTime>0</agnt:lastHeartBeatTime>
        <agnt:durationForUnavailability>180</agnt:durationForUnavailability>
        <agnt:lastJobTransfer>true</agnt:lastJobTransfer>
        <agnt:isPermitted>true</agnt:isPermitted>
        <agnt:jobTransferFailureTime>0</agnt:jobTransferFailureTime>
        <agnt:workspacePath>D:\user\hakan\TlosSW</agnt:workspacePath>
        <agnt:locals>
            <par:parameter id="91">
                <par:name>JAVAPATH</par:name>
                <par:valueString>D:\dev\Java\jdk1.6.0_21\bin\</par:valueString>
                <par:preValue type="2">D:\dev\Java\jdk1.6.0_21\bin\</par:preValue>
                <par:desc>JAVA PATH</par:desc>
            </par:parameter>
        </agnt:locals>
    </agnt:SWAgent>
    <agnt:SWAgent id="17">
        <res:Resource>merve-laptop</res:Resource>
        <agnt:osType>Windows</agnt:osType>
        <agnt:agentType>agent</agnt:agentType>
        <agnt:nrpePort>5666</agnt:nrpePort>
        <agnt:jmxTlsPort>3001</agnt:jmxTlsPort>
        <agnt:jmxUser>jmxuser</agnt:jmxUser>
        <agnt:jmxPassword>jmxpaswd</agnt:jmxPassword>
        <agnt:inJmxAvailable>false</agnt:inJmxAvailable>
        <agnt:outJmxAvailable>false</agnt:outJmxAvailable>
        <agnt:jmxAvailable>false</agnt:jmxAvailable>
        <agnt:userStopRequest>null</agnt:userStopRequest>
        <agnt:nrpeAvailable>false</agnt:nrpeAvailable>
        <agnt:lastHeartBeatTime>0</agnt:lastHeartBeatTime>
