=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xsds/tlosSWAlarm_v_1_0.xsd
<xs:schema xmlns:dat="http://www.likyateknoloji.com/XML_data_types" xmlns="http://www.likyateknoloji.com/XML_alarm_types" xmlns:com="http://www.likyateknoloji.com/XML_common_types" xmlns:state-types="http://www.likyateknoloji.com/state-types" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sla="http://www.likyateknoloji.com/XML_SLA_types" xmlns:usr="http://www.likyateknoloji.com/XML_user_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" elementFormDefault="qualified" targetNamespace="http://www.likyateknoloji.com/XML_alarm_types">
    <xs:import namespace="http://www.likyateknoloji.com/XML_SLA_types" schemaLocation="tlosSWSLA_v_1_0.xsd"/>
    <xs:import namespace="http://www.likyateknoloji.com/XML_common_types" schemaLocation="tlosSWOrtak_v_1_0.xsd"/>
    <xs:import namespace="http://www.likyateknoloji.com/XML_user_types" schemaLocation="tlosSWUser_v_1_0.xsd"/>
    <xs:import namespace="http://www.likyateknoloji.com/state-types" schemaLocation="tlosSWState_v_1_0.xsd"/>
    <xs:import namespace="http://www.likyateknoloji.com/XML_data_types" schemaLocation="tlosSWData_v_1_0.xsd"/>
    <xs:element name="alarmManagement">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="alarm"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="alarm">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="desc"/>
                <xs:element ref="alarmType"/>
                <xs:element ref="subscriptionType"/>
                <xs:element ref="creationDate"/>
                <xs:element ref="startDate"/>
                <xs:element ref="endDate"/>
                <xs:element ref="com:timeZone" minOccurs="0"/>
                <xs:element ref="com:typeOfTime" minOccurs="0"/>
                <xs:element ref="level"/>
                <xs:element ref="subscriber"/>
                <xs:element ref="focus"/>
                <xs:element ref="caseManagement"/>
            </xs:sequence>
            <xs:attribute name="ID" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="desc" type="xs:string"/>
    <xs:element name="creationDate" type="xs:dateTime"/>
    <xs:element name="startDate" type="xs:dateTime"/>
    <xs:element name="endDate" type="xs:dateTime"/>
    <xs:element name="level" type="xs:integer"/>
    <xs:element name="subscriber">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element ref="person"/>
                    <xs:element ref="com:role"/>
                </xs:choice>
                <xs:element ref="alarmChannelTypes" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="focus">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="jobs" minOccurs="0"/>
                <xs:element ref="scenarios" minOccurs="0"/>
                <xs:element ref="systems" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jobs">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="job"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="alarmChannelTypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="warnBy"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="warnBy">
        <xs:complexType>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="alarmType" default="Job">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Job"/>
                <xs:enumeration value="Scenario"/>
                <xs:enumeration value="System"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="subscriptionType" default="User">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="User"/>
                <xs:enumeration value="Role"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="person">
        <xs:complexType>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="job">
        <xs:complexType>
            <xs:attribute name="id" use="required" type="xs:integer"/>
            <xs:attribute name="depth" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="scenarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="scenario"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="scenario">
        <xs:complexType>
            <xs:attribute name="id" use="required" type="xs:integer"/>
            <xs:attribute name="depth" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="systems">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="system"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="system">
        <xs:complexType>
            <xs:attribute name="entry-name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="caseManagement">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="systemManagement"/>
                <xs:element minOccurs="0" ref="stateManagement"/>
                <xs:element minOccurs="0" ref="SLAManagement"/>
                <xs:element minOccurs="0" ref="timeManagement"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="systemManagement">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sla:Hardware"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="stateManagement">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="state-types:LiveStateInfo"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	<!--xs:element name="SLAManagement">
		<xs:complexType>
			<xs:attribute name="control" use="required" type="xs:NCName"/>
		</xs:complexType>
	</xs:element-->
    <xs:element name="SLAManagement" default="NO">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="YES"/>
                <xs:enumeration value="NO"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="timeManagement">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="timeOutControl"/>
                <xs:element ref="tolerancePercentage"/>
                <xs:element ref="minPercentage"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="timeOutControl" type="xs:boolean"/>
    <xs:element name="tolerancePercentage" type="xs:boolean"/>
    <xs:element name="minPercentage" type="xs:boolean"/>
</xs:schema>

=== likyateknoloji/TlosSWGroup/TlosSW_V1.0_Schema/dbfiles/xml/tlosSWAlarm10.xml
<!-- Created for the TLOS Scheduler http://www.likyateknoloji.com -->
<alm:alarmManagement xmlns:com="http://www.likyateknoloji.com/XML_common_types" xmlns:state-types="http://www.likyateknoloji.com/state-types" xmlns:sla="http://www.likyateknoloji.com/XML_SLA_types" xmlns:usr="http://www.likyateknoloji.com/XML_user_types" xmlns:alm="http://www.likyateknoloji.com/XML_alarm_types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.likyateknoloji.com/XML_alarm_types xmldb:exist:///db/TLOSSW/xsds/tlosSWAlarm_v_1_0.xsd">
    <alarm xmlns="http://www.likyateknoloji.com/XML_alarm_types" ID="134">
        <alm:name>alarm37</alm:name>
        <alm:desc>Alarm Kaw</alm:desc>
        <alm:alarmType>Job</alm:alarmType>
        <alm:subscriptionType>User</alm:subscriptionType>
        <alm:creationDate>2012-12-24T16:18:46.890+02:00</alm:creationDate>
        <alm:startDate>2012-12-01T16:18:46.890+02:00</alm:startDate>
        <alm:endDate>2012-12-25T16:18:46.891+02:00</alm:endDate>
        <alm:level>2</alm:level>
        <alm:subscriber>
            <person id="4"/>
            <alarmChannelTypes>
                <warnBy id="1"/>
                <warnBy id="2"/>
            </alarmChannelTypes>
        </alm:subscriber>
        <alm:focus>
            <jobs>
                <job id="2" depth="26"/>
                <job id="7" depth="26"/>
            </jobs>
        </alm:focus>
        <alm:caseManagement>
            <stateManagement>
                <state-types:LiveStateInfo LSIDateTime="2012-12-24T16:18:46.891+0200">
                    <state-types:StateName>PENDING</state-types:StateName>
                    <state-types:SubstateName>CREATED</state-types:SubstateName>
                    <state-types:StatusName>SUCCESS</state-types:StatusName>
                </state-types:LiveStateInfo>
            </stateManagement>
            <timeManagement>
                <timeOutControl>false</timeOutControl>
                <tolerancePercentage>false</tolerancePercentage>
                <minPercentage>true</minPercentage>
            </timeManagement>
        </alm:caseManagement>
    </alarm>
    <alarm xmlns="http://www.likyateknoloji.com/XML_alarm_types" ID="136">
        <alm:name>Alarm9</alm:name>
        <alm:desc>Alarm99</alm:desc>
        <alm:alarmType>Job</alm:alarmType>
        <alm:subscriptionType>User</alm:subscriptionType>
        <alm:creationDate>2012-12-24T16:24:26.666+02:00</alm:creationDate>
        <alm:startDate>2012-12-02T16:24:26.666+02:00</alm:startDate>
        <alm:endDate>2012-12-25T16:24:26.666+02:00</alm:endDate>
        <alm:level>1</alm:level>
        <alm:subscriber>
            <person id="1"/>
            <alarmChannelTypes>
                <warnBy id="1"/>
            </alarmChannelTypes>
        </alm:subscriber>
        <alm:focus>
            <jobs>
                <job id="2" depth="32"/>
            </jobs>
        </alm:focus>
        <alm:caseManagement>
            <stateManagement>
                <state-types:LiveStateInfo LSIDateTime="2012-12-24T16:24:26.667+0200">
                    <state-types:StateName>PENDING</state-types:StateName>
                    <state-types:SubstateName>CREATED</state-types:SubstateName>
                    <state-types:StatusName>SUCCESS</state-types:StatusName>
                </state-types:LiveStateInfo>
            </stateManagement>
            <timeManagement>
                <timeOutControl>false</timeOutControl>
                <tolerancePercentage>false</tolerancePercentage>
                <minPercentage>true</minPercentage>
            </timeManagement>
        </alm:caseManagement>
    </alarm>
</alm:alarmManagement>
